#!/bin/bash
TAB="  "
INFO="${TAB}ℹ️${TAB}${X}"
START="${TAB}▶️${TAB}${X}"
OK="${TAB}✅${TAB}${X}"
NOTOK="${TAB}❌${TAB}${X}"
WARN="${TAB}⚠️${TAB}${X}"
DISK="${TAB}💾${TAB}${X}"
CONSOLE="${TAB}📟${TAB}${X}"
ROBOT="${TAB}🤖${TAB}${X}"

ZERO="${TAB}0️⃣${TAB}${X}"
ONE="${TAB}1️⃣${TAB}${X}"
TWO="${TAB}2️⃣${TAB}${X}"
THREE="${TAB}3️⃣${TAB}${X}"
FOUR="${TAB}4️⃣${TAB}${X}"
FIVE="${TAB}5️⃣${TAB}${X}"
SIX="${TAB}6️⃣${TAB}${X}"
SEVEN="${TAB}7️⃣${TAB}${X}"
EIGHT="${TAB}8️⃣${TAB}${X}"
NINE="${TAB}9️⃣${TAB}${X}"
TEN="${TAB}🔟${TAB}${X}"
